### ISSUE TITLE
请问怎么获取实时提取的id-title键值

### ISSUE THREAD

**Issue by QiXingRan** [mcxiaoxiao/xiaohongshuCrawler#1]
如题，感谢回复

**Comment by mcxiaoxiao** [comment]
Thank you for your submission! 😊

We noticed that our crawler for xiaohongshu.com was not functioning due to changes in the webpage structure, which caused the tag matching to fail. We have updated the relevant JavaScript and released it on Greasy Fork. You can update to version v0.2 as of 2024.11.29. It should now correctly output the ID-title key-value pairs.

Please note that direct access via explore/id might not work, but the links in the console are still usable. If needed, you can manually modify the script to replace with the console links.

感谢您的提交！😊

我们注意到，由于网页结构的变更，导致我们在小红书上的爬虫失效。我们已经更新了相关 JavaScript，并在 Greasy Fork 上发布。您可以更新至 2024.11.29 的 v0.2 版本，现在应该可以正常输出 ID-标题 键值对。

请注意，直接通过 explore/id 访问可能无法直接访问，但控制台中的链接仍然可用。如有需要，您可以手动修改脚本以替换为控制台中的链接。
![image](https://github.com/user-attachments/assets/8531417f-56c4-4e05-b00b-fd5b76e871e7)
